using System;
using System.Configuration;
using System.IO;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;

using Org.BouncyCastle.Asn1.X509;
using Org.BouncyCastle.Crypto;
using Org.BouncyCastle.Crypto.Generators;
using Org.BouncyCastle.Crypto.Operators;
using Org.BouncyCastle.Crypto.Parameters;
using Org.BouncyCastle.Math;
using Org.BouncyCastle.Pkcs;
using Org.BouncyCastle.Security;
using Org.BouncyCastle.X509;

using BcX509Certificate = Org.BouncyCastle.X509.X509Certificate;

namespace miPDFsign.Helpers
{
    /// <summary>
    /// Manages the RSA certificate used to encrypt biometric signature data.
    ///
    /// Priority:
    ///   1. If <c>BiometricCertPath</c> (App.config) points to an existing PFX → load it
    ///      (nothing is written to disk).
    ///   2. Otherwise: generate a fresh RSA-3072 self-signed key pair <b>in memory</b>. The
    ///      matching PFX is written later via <see cref="SaveAutoGeneratedPfx"/> — after the
    ///      final save location is known — so it can be named after the saved document and
    ///      placed next to it (<c>&lt;DocumentName&gt;_bioCert.pfx</c>).
    /// </summary>
    public static class BiometricCertManager
    {
        // Cached key pair for the current process lifetime
        private static AsymmetricCipherKeyPair? _keyPair;
        private static BcX509Certificate?       _cert;
        private static bool                     _autoGenerated;   // true = generated here (PFX must be persisted)
        private static readonly object          _lock = new();

        // ----------------------------------------------------------------
        //  Public API
        // ----------------------------------------------------------------

        /// <summary>
        /// Returns the RSA public key used to encrypt biometric data.
        /// Loads the configured certificate or generates a key pair in memory if needed.
        /// </summary>
        public static RsaKeyParameters GetEncryptionPublicKey()
        {
            EnsureKeyPair();
            return (RsaKeyParameters)_keyPair!.Public;
        }

        /// <summary>
        /// Returns the RSA private key for decrypting / verifying biometric data (forensic use).
        /// </summary>
        public static RsaKeyParameters? GetDecryptionPrivateKey()
        {
            if (_keyPair == null) return null;
            return (RsaKeyParameters)_keyPair.Private;
        }

        /// <summary>
        /// Persists the <b>auto-generated</b> biometric key as
        /// <c>&lt;docBaseName&gt;_bioCert.pfx</c> in <paramref name="dir"/>. Call this once the
        /// final save location of the signed document is known.
        /// No-op when the certificate was loaded from <c>BiometricCertPath</c> (nothing to
        /// persist) or when no key has been generated yet.
        /// </summary>
        public static void SaveAutoGeneratedPfx(string? dir, string? docBaseName)
        {
            lock (_lock)
            {
                if (!_autoGenerated || _keyPair == null || _cert == null) return;

                string saveDir = !string.IsNullOrWhiteSpace(dir) && Directory.Exists(dir)
                    ? dir
                    : AppDomain.CurrentDomain.BaseDirectory;

                // Name the PFX after the saved document (e.g. "Invoice_bioCert.pfx").
                string safeBase = docBaseName ?? "";
                foreach (char c in Path.GetInvalidFileNameChars())
                    safeBase = safeBase.Replace(c, '_');
                string fileName = string.IsNullOrWhiteSpace(safeBase)
                    ? "biometric_key.pfx"
                    : safeBase + "_bioCert.pfx";
                string pfxPath = Path.Combine(saveDir, fileName);

                try
                {
                    var random = new SecureRandom();
                    var store  = new Pkcs12StoreBuilder().Build();
                    var certEntry = new X509CertificateEntry(_cert);
                    store.SetCertificateEntry("biometric", certEntry);
                    store.SetKeyEntry("biometric", new AsymmetricKeyEntry(_keyPair.Private),
                        new[] { certEntry });

                    using var fs = new FileStream(pfxPath, FileMode.Create, FileAccess.Write);
                    store.Save(fs, Array.Empty<char>(), random);
                    AppLogger.Info($"BiometricCertManager: biometric PFX saved to '{pfxPath}'");
                }
                catch (Exception ex)
                {
                    AppLogger.Warn($"BiometricCertManager: could not save biometric PFX to '{pfxPath}': {ex.Message}");
                }
            }
        }

        // ----------------------------------------------------------------
        //  Internal
        // ----------------------------------------------------------------

        private static void EnsureKeyPair()
        {
            lock (_lock)
            {
                if (_keyPair != null) return;

                string certPath = ConfigurationManager.AppSettings["BiometricCertPath"] ?? "";
                string certPass = ConfigurationManager.AppSettings["BiometricCertPassword"] ?? "";

                if (!string.IsNullOrWhiteSpace(certPath) && File.Exists(certPath))
                {
                    LoadFromPfx(certPath, certPass);
                    _autoGenerated = false;
                    AppLogger.Info($"BiometricCertManager: loaded cert from '{certPath}'");
                }
                else
                {
                    GenerateInMemory();
                    _autoGenerated = true;
                }
            }
        }

        private static void LoadFromPfx(string pfxPath, string password)
        {
            // Use .NET's X509Certificate2 to read the PFX, then convert to BouncyCastle
            var cert2 = new X509Certificate2(pfxPath, password,
                X509KeyStorageFlags.Exportable | X509KeyStorageFlags.EphemeralKeySet);

            // Export public certificate bytes → BouncyCastle parser
            var parser = new X509CertificateParser();
            _cert = parser.ReadCertificate(cert2.RawData);

            // Export private key → BouncyCastle (requires RSA)
            using var rsa = cert2.GetRSAPrivateKey()
                ?? throw new InvalidOperationException(
                    "BiometricCertManager: PFX does not contain an RSA private key.");

            RSAParameters rsaParams = rsa.ExportParameters(includePrivateParameters: true);
            _keyPair = new AsymmetricCipherKeyPair(
                DotNetUtilities.GetRsaPublicKey(rsa),
                DotNetUtilities.GetRsaKeyPair(rsaParams).Private);
        }

        private static void GenerateInMemory()
        {
            AppLogger.Info("BiometricCertManager: no cert configured – generating RSA-3072 self-signed cert (in memory)");

            var random = new SecureRandom();
            var keyGen = new RsaKeyPairGenerator();
            keyGen.Init(new KeyGenerationParameters(random, 3072));
            _keyPair = keyGen.GenerateKeyPair();

            var certGen = new X509V3CertificateGenerator();
            var dn = new X509Name("CN=miPDFsign Biometric Key");
            certGen.SetIssuerDN(dn);
            certGen.SetSubjectDN(dn);
            certGen.SetSerialNumber(new BigInteger(128, random));
            certGen.SetNotBefore(DateTime.UtcNow.AddSeconds(-5));
            certGen.SetNotAfter(DateTime.UtcNow.AddYears(20));
            certGen.SetPublicKey(_keyPair.Public);
            _cert = certGen.Generate(
                new Asn1SignatureFactory("SHA256WITHRSA", _keyPair.Private, random));
        }
    }
}
